import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo list App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='relative flex min-h-screen flex-col bg-background'>

          <main className='flex-1'>
            <div className='container flex-1 mx-auto'>
              {children}
            </div>
          </main>
          {/* <Footer /> */}

        </div>
      </body>
    </html>
  );
}
